Repository nomad-coe/nomad-simulations, pull requests merged in 2024-04, with the labels that each got.

#38 Quick fix ide
  README.md
  tests/conftest.py
Labels: improvement/fix

#53 Add BandGap output
  src/nomad_simulations/outputs.py
  src/nomad_simulations/physical_property.py
  src/nomad_simulations/properties/__init__.py
  src/nomad_simulations/properties/band_gap.py
  src/nomad_simulations/variables.py
  tests/conftest.py
  tests/test_band_gap.py
  tests/test_outputs.py
  tests/test_physical_properties.py
Labels: new feature

#57 Fix minor things
  nomad.yaml
  pyproject.toml
  src/nomad_simulations/outputs.py
  src/nomad_simulations/physical_property.py
  src/nomad_simulations/properties/band_gap.py
  src/nomad_simulations/variables.py
  tests/test_band_gap.py
  tests/test_variables.py
Labels: improvement/fix

#24 Documentation Part I - General docu
  README.md
  docs/assets/program.png
  docs/assets/simulation.png
  docs/assets/simulation_base.png
  docs/assets/simulation_composition.png
  docs/contact.md
  docs/general.md
  docs/howto_use.md
  docs/index.md
  docs/model_method/model_method.md
  docs/model_system/model_system.md
  docs/normalize.md
  docs/outputs/outputs.md
  docs/stylesheets/extra.css
  mkdocs.yml
  pyproject.toml
Labels: documentation

#15 Adding unit testing for ModelSystem and AtomsState
  .github/workflows/actions.yaml
  pyproject.toml
  src/nomad_simulations/atoms_state.py
  src/nomad_simulations/model_system.py
  src/nomad_simulations/utils/utils.py
  tests/conftest.py
  tests/test_atoms_state.py
  tests/test_band_gap.py
  tests/test_energies.py
  tests/test_model_system.py
  tests/test_outputs.py
  tests/test_physical_properties.py
  tests/test_spectral_profile.py
  tests/test_utils.py
  tests/test_variables.py
Labels: testing
