Repository nomad-coe/nomad-simulations, pull requests merged in 2025-08, with the labels that each got.

#206 Extend docs on workflows
  docs/general.md
Labels: documentation

#201 Physical property tweaking
  src/nomad_simulations/schema_packages/outputs.py
  src/nomad_simulations/schema_packages/physical_property.py
  src/nomad_simulations/schema_packages/properties/__init__.py
  src/nomad_simulations/schema_packages/properties/band_gap.py
  src/nomad_simulations/schema_packages/properties/band_structure.py
  src/nomad_simulations/schema_packages/properties/energies.py
  src/nomad_simulations/schema_packages/properties/fermi_surface.py
  src/nomad_simulations/schema_packages/properties/forces.py
  src/nomad_simulations/schema_packages/properties/greens_function.py
  src/nomad_simulations/schema_packages/properties/hopping_matrix.py
  src/nomad_simulations/schema_packages/properties/permittivity.py
  src/nomad_simulations/schema_packages/properties/spectral_profile.py
  src/nomad_simulations/schema_packages/properties/thermodynamics.py
  src/nomad_simulations/schema_packages/variables.py
  tests/properties/test_band_gap.py
  tests/properties/test_band_structure.py
  tests/properties/test_energies.py
  tests/properties/test_fermi_surface.py
  tests/properties/test_forces.py
  tests/properties/test_hopping_matrix.py
  tests/properties/test_permittivity.py
  tests/properties/test_spectral_profile.py
  tests/test_outputs.py
  tests/test_physical_properties.py
  tests/test_variables.py
Labels: improvement/fix

#227 temporary fix: 'molecule / cluster' breaks ModelSystem.type enum
  src/nomad_simulations/schema_packages/model_system.py
  tests/test_model_system.py
Labels: bug, ModelSystem
